name: Build

on:
  push:
    branches: ['**']
    tags: ['**']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.1.0

      - name: Dependency Review
        uses: actions/dependency-review-action@v2.5.1
        if: github.event_name == 'pull_request'

      - name: Use Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16.x
          cache: 'npm'

      - run: npm ci

      - run: npm run lint

      - run: CONFIG_FILE=arn:aws:s3:::bucket/key npm run cdk -- synth
